### ISSUE TITLE
SSL pinning

### ISSUE THREAD

**Issue by guptamitesh** [Lightstreamer/Lightstreamer-lib-client-swift#1]
Hi, 
I see lightstreamer internally uses almofire and starscream both supoorts ssl pinning. Can we expose the same while connecting the lsclient to server.

**Comment by acarioni** [comment]
As far as we know, HTTP Public Key Pinning is no longer a recommended feature (see this [warning](https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning) on MDN) and it has been removed from all modern browsers for example.
Is there any particular reason you need it?

**Comment by guptamitesh** [comment]
Thanks for the reply, I went through the link provided in the comment above and the only browser which seems to be supporting it is firefox for android so I will say the method has still not picked up. Giving an option for SSL pinning should be simple and let it will be on clients to use it or not. Let me know your thoughts.


![image](https://user-images.githubusercontent.com/13232814/135276838-b1e18e86-1707-49b5-83e8-86bbbe4307eb.png)

**Comment by guptamitesh** [comment]
Also ssl pinning does not work like HTTP Public Key Pinning as for ssl pinning we dont need a server side change or enabling something in server. SSL pinning happen by pre letting client know about server certificates so that man in the middle attack or data changes via a proxy like charles or other can be prevented.

**Comment by acarioni** [comment]
I’ve made some investigations on SSL pinning support by Alamofire and Starscream.
While Alamofire definitely supports it, I’m not sure whether the same is true for Starscream.
For example there are a lot of [questions](https://github.com/daltoniam/Starscream/issues?q=%22ssl+pinning%22) about pinning without answer or vaguely addressed.
Do you have any experience on SSL pinning in Starscream 4.x by chance?

**Comment by guptamitesh** [comment]
on the github they clearly mention it:
https://github.com/daltoniam/Starscream#ssl-pinning

**Comment by acarioni** [comment]
Yes, but they don’t provide any explanations about how one could configure it.
