### ISSUE TITLE
If two subscriptions contain same properties, how to identify it

### ISSUE THREAD

**Issue by LFate** [Lightstreamer/Lightstreamer-lib-client-swift#3]
`func subscription(_ subscription: Subscription, didUpdateItem itemUpdate: ItemUpdate)`
if this func receive update, and two subs contain same fieldSchema、items、etc. , how can I know they are different.
Is there any thing like "ID" that I can use?

**Comment by acarioni** [comment]
You can install two [SubscriptionDelegates](https://sdk.lightstreamer.com/ls-swift-client/6.0.0/api/Classes/Subscription.html#/s:19LightstreamerClient12SubscriptionC11addDelegateyyAA0cE0_pF), one for each Subscription, or you can install only one delegate and then tell the difference between the Subscriptions by using the [identity operators](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/classesandstructures#Identity-Operators).

But please use the [community forum](https://forums.lightstreamer.com) for questions like this.
