### ISSUE TITLE
Error 61, Expected 1 items but got 2

### ISSUE THREAD

**Issue by casthegrinni** [Lightstreamer/Lightstreamer-lib-client-swift#4]
I'm using SubscriptionDelegate and I'm getting an error with my implementation.
Specific using RAW mode, I receive this error inside 
"subscription(_ subscription: Subscription, didFailWithErrorCode code: Int, message: String?)"

Have you any idea why i'm receiving this error?

**Subscription:** [
mode: RAW,
items: ["NOTIFICATION"],
fields: ["id_notification", "cd_priority", "ds_title", "ds_body", "ds_action", "dh_notification", "notification_type"],
dataAdapter: MY_ADAPTER]
**Code:** 61
**Message:** "Expected 1 items but got 2"

**Comment by acarioni** [comment]
The error indicates that the number of items returned by the server does not match the number of items specified by the client. Please check the implementation of the Metadata Adapter method [getItems](https://sdk.lightstreamer.com/ls-adapter-inprocess/7.2.0/api/com/lightstreamer/interfaces/metadata/MetadataProvider.html#getItems-java.lang.String-java.lang.String-java.lang.String-) and ensure that it returns exactly one item corresponding to the item name NOTIFICATION.
